/**
 * Terrain: a height map of length CANVAS_WIDTH (one y-height per x-column),
 * generated by midpoint displacement and deformed on explosions (SPEC §4.1).
 *
 * Convention (shared by all agents): smaller terrain[x] = taller hill (surface
 * higher on screen, since y grows downward). Ground occupies y from terrain[x]
 * down to CANVAS_HEIGHT. A point (x, y) is underground when y >= terrain[floor(x)].
 *
 * Determinism: all randomness here comes from a SEEDED PRNG (mulberry32) seeded
 * from the `seed` argument. No wall-clock reads, no global Math.random — same
 * seed always yields an identical height map.
 */

export const CANVAS_WIDTH = 800;
export const CANVAS_HEIGHT = 500;

/** Surface kept within these vertical bounds so tanks have sky above / ground below. */
const MIN_SURFACE_Y = Math.floor(CANVAS_HEIGHT * 0.35); // 175 — tallest allowed hill
const MAX_SURFACE_Y = Math.floor(CANVAS_HEIGHT * 0.9); //  450 — lowest allowed valley

/**
 * Seeded PRNG (mulberry32). Deterministic, fast, good enough for terrain gen.
 * Returns a function yielding floats in [0, 1).
 */
function mulberry32(seed: number): () => number {
  let a = seed;
  return function (): number {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Clamp a number to an inclusive range. */
function clamp(v: number, lo: number, hi: number): number {
  return v < lo ? lo : v > hi ? hi : v;
}

/**
 * Fold an arbitrary caller-supplied seed (which may be a float, negative, NaN,
 * Infinity, or larger than 2^32) into a well-mixed uint32. This avoids silent
 * seed collisions: a bare `seed >>> 0` would collapse all of NaN/0/-0/Infinity/
 * 2^32 to seed 0 and alias seeds differing only above bit 32. Deterministic —
 * pure integer mixing, no clock or global random.
 */
function hashSeed(seed: number): number {
  // Map any non-finite seed to a defined fallback so NaN/Infinity are stable
  // and distinct from a typical small integer seed.
  const n = Number.isFinite(seed) ? seed : 0x9e3779b9;
  // Capture the fractional part and both 32-bit halves of large integers so
  // floats and seeds > 2^32 don't alias.
  const frac = Math.floor((n - Math.floor(n)) * 0x100000000) >>> 0;
  const lo = Math.floor(n) | 0;
  const hi = Math.floor(n / 0x100000000) | 0;
  let h = (lo ^ frac ^ Math.imul(hi, 0x85ebca6b)) >>> 0;
  // Final avalanche (MurmurHash3 fmix32).
  h ^= h >>> 16;
  h = Math.imul(h, 0x85ebca6b);
  h ^= h >>> 13;
  h = Math.imul(h, 0xc2b2ae35);
  h ^= h >>> 16;
  return h >>> 0;
}

/**
 * Generate a reproducible height map via 1D midpoint displacement
 * (diamond-square variant). Endpoints are seeded randomly, then each segment is
 * recursively split: the midpoint height is the average of its endpoints plus a
 * random displacement whose magnitude halves at each level of recursion.
 *
 * @param seed RNG seed for reproducible terrain. Same seed => identical array;
 *             different seeds => different terrain.
 * @returns Height map of length CANVAS_WIDTH, each value the surface y for that
 *          column, within roughly [MIN_SURFACE_Y, MAX_SURFACE_Y].
 */
export function generate(seed: number): Uint16Array {
  // Hash the caller seed into a well-mixed uint32 so distinct seeds (including
  // floats and out-of-range values) map to distinct terrain.
  const rand = mulberry32(hashSeed(seed));
  const n = CANVAS_WIDTH;

  // Work on a power-of-two-plus-one grid so midpoint displacement subdivides
  // cleanly, then sample the first CANVAS_WIDTH columns out of it.
  let size = 1;
  while (size + 1 < n) size *= 2;
  const gridLen = size + 1; // (2^k) + 1 points

  const heights = new Float64Array(gridLen);

  const span = MAX_SURFACE_Y - MIN_SURFACE_Y;
  const mid = MIN_SURFACE_Y + span / 2;

  // Random endpoints near the middle of the allowed band.
  heights[0] = mid + (rand() - 0.5) * span * 0.5;
  heights[gridLen - 1] = mid + (rand() - 0.5) * span * 0.5;

  // Initial displacement magnitude; roughness controls how the magnitude decays
  // per level (0.5 => classic midpoint displacement / Hurst exponent ~1).
  let displacement = span * 0.6;
  const roughness = 0.5;

  for (let step = size; step > 1; step = Math.floor(step / 2)) {
    const half = Math.floor(step / 2);
    for (let i = half; i < gridLen; i += step) {
      const left = heights[i - half];
      const right = heights[i + half];
      const avg = (left + right) / 2;
      heights[i] = avg + (rand() - 0.5) * 2 * displacement;
    }
    displacement *= roughness;
  }

  // Sample / clamp into the output column array.
  const terrain = new Uint16Array(n);
  for (let x = 0; x < n; x++) {
    // Map column x in [0, n) onto the grid [0, gridLen-1]. gridLen is always
    // (2^k)+1 >= 2 for CANVAS_WIDTH=800, so n-1 is never 0 here.
    const gx = Math.round((x * (gridLen - 1)) / (n - 1));
    const y = clamp(heights[gx], MIN_SURFACE_Y, MAX_SURFACE_Y);
    terrain[x] = Math.round(y);
  }

  return terrain;
}

/**
 * Crater the terrain at (cx, cy) with radius r by lowering the surface in
 * [cx-r, cx+r] by the circular chord depth at each column (SPEC §4.1).
 *
 * Lowering the surface means terrain[x] INCREASES (larger y = lower on screen).
 * The carve is the vertical extent of the blast circle at column x, i.e. the
 * chord height 2*sqrt(r^2 - dx^2). Result is clamped to [0, CANVAS_HEIGHT].
 *
 * Deterministic: depends only on its arguments. `cy` is accepted for signature
 * stability / future shaping but the MVP0 crater is a symmetric circular bite
 * independent of impact height.
 *
 * Returns the inclusive [xStart, xEnd] column range it actually modified (or
 * null if nothing was carved) so callers (e.g. GameEngine.explode) can mirror
 * exactly the affected span into the serialized terrain instead of
 * independently re-deriving the bounds — which would silently desync if these
 * bounds ever change.
 */
export function deform(
  terrain: Uint16Array,
  cx: number,
  cy: number,
  r: number,
): { xStart: number; xEnd: number } | null {
  void cy;
  if (r <= 0) return null;

  const r2 = r * r;
  const xStart = Math.max(0, Math.ceil(cx - r));
  const xEnd = Math.min(CANVAS_WIDTH - 1, Math.floor(cx + r));
  if (xStart > xEnd) return null;

  for (let x = xStart; x <= xEnd; x++) {
    const dx = x - cx;
    const inside = r2 - dx * dx;
    if (inside <= 0) continue;
    // Full vertical chord of the blast circle at this column.
    const depth = 2 * Math.sqrt(inside);
    const lowered = clamp(terrain[x] + depth, 0, CANVAS_HEIGHT);
    terrain[x] = Math.round(lowered);
  }
  return { xStart, xEnd };
}

/**
 * Resolve unsupported tanks after deformation: any tank whose base is above the
 * terrain surface falls under gravity until grounded (SPEC §4.1).
 *
 * MVP0 has no tank entities wired through here yet; this is a no-op placeholder
 * kept for signature stability so GameEngine can call it once collapse lands in
 * MVP1. Returns true if any tank moved.
 */
export function collapse(terrain: Uint16Array): boolean {
  void terrain;
  return false;
}

/** Terrain surface y at a given x-column (O(1) lookup). */
export function heightAt(terrain: Uint16Array, x: number): number {
  return terrain[Math.floor(x)];
}

/**
 * Surface y at a given (possibly fractional) x. Alias of heightAt with bounds
 * clamping — convenient for renderer/physics callers that hold a float x.
 */
export function surfaceAt(terrain: Uint16Array, x: number): number {
  const xi = clamp(Math.floor(x), 0, terrain.length - 1);
  return terrain[xi];
}
