/**
 * Terrain: a height map of length CANVAS_WIDTH (one y-height per x-column),
 * generated by midpoint displacement and deformed on explosions (SPEC §4.1).
 */

export const CANVAS_WIDTH = 800;
export const CANVAS_HEIGHT = 500;

/**
 * Generate a reproducible height map via midpoint displacement.
 * @param seed RNG seed for reproducible terrain.
 * @returns Height map of length CANVAS_WIDTH.
 */
export function generate(seed: number): Uint16Array {
  void seed;
  throw new Error('not implemented');
}

/**
 * Crater the terrain at (cx, cy) with radius r by subtracting a circular chord
 * from each affected column (SPEC §4.1).
 */
export function deform(
  terrain: Uint16Array,
  cx: number,
  cy: number,
  r: number,
): void {
  void terrain;
  void cx;
  void cy;
  void r;
  throw new Error('not implemented');
}

/**
 * Resolve unsupported tanks after deformation: any tank whose base is above the
 * terrain surface falls under gravity until grounded (SPEC §4.1). Returns true
 * if any tank moved.
 */
export function collapse(terrain: Uint16Array): boolean {
  void terrain;
  throw new Error('not implemented');
}

/** Terrain surface height at a given x-column (O(1) lookup). */
export function heightAt(terrain: Uint16Array, x: number): number {
  return terrain[Math.floor(x)];
}
