/** WB-03 regression witnesses, not autogenerated balance expectations. */
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { WEAPONS } from '../../shared/src/engine/WeaponSystem.ts';
import { computeAiPlan } from '../../shared/src/engine/AI.ts';
import { makeExchangeFixture, sampleShieldExchange } from '../balance/shieldExchange.mjs';
import { makeOpeningShieldFixture, compareOpeningShield, runOpeningShieldStudy } from '../balance/openingShield.mjs';

const stock = makeOpeningShieldFixture('open-42');
const candidate = makeOpeningShieldFixture('open-42', 'no-free-heavy');
const untouched = structuredClone(stock.engine.getState());
const catalog = structuredClone(WEAPONS);
const candidateState = structuredClone(candidate.engine.getState());
for (const tank of candidateState.tanks) tank.inventory.heavy_shield.count = 1;
assert.deepEqual(candidateState, untouched, 'only finite heavy stock changes on the two starting tanks');
assert.equal(candidate.changes.length, 2);
assert.equal(stock.changes.length, 0);
assert.equal(makeExchangeFixture('open-42').engine.getState().tanks[0].inventory.heavy_shield.count, 1,
  'stock constructor and live opening remain unchanged');

const fixedAim = { angle: 180, power: 100 }; // Pinned deliberate misses for turn/cash accounting.
const fixtureOptions = { fixedAim, commitmentsPerSeat: 4, weapon: 'missile' };
const fireBefore = sampleShieldExchange(stock.engine, fixtureOptions);
const fireAfter = sampleShieldExchange(candidate.engine, fixtureOptions);
assert.equal(compareOpeningShield(fireBefore, fireAfter).status, 'control-identical');
assert.equal(fireBefore.trace.length, 8);
assert.deepEqual(fireBefore.commitments, { p1: 4, p2: 4 });
assert.equal(fireBefore.termination, 'horizon');
assert.equal(fireBefore.summary.winner, null, 'censored horizon does not become a winner');
assert.equal(fireBefore.summary.tanks[0].earnedCredits, 2000);

const shieldOptions = { ...fixtureOptions, strategy: 'held-shield-first' };
const heavy = sampleShieldExchange(stock.engine, shieldOptions);
const normal = sampleShieldExchange(candidate.engine, shieldOptions);
assert.equal(heavy.trace[0].weapon, 'heavy_shield');
assert.equal(normal.trace[0].weapon, 'shield');
assert.equal(heavy.summary.tanks[0].shieldHp, 240);
assert.equal(normal.summary.tanks[0].shieldHp, 120);
assert.equal(heavy.summary.tanks[0].shots, 3);
assert.equal(normal.summary.tanks[0].shots, 3);
assert.equal(normal.summary.tanks[0].earnedCredits, 1500);
assert.equal(heavy.purchases.length, 0);
assert.equal(normal.purchases.length, 0);
const comparison = compareOpeningShield(heavy, normal);
assert.equal(comparison.status, 'compared');
assert.equal(comparison.subjectShieldDelta, -120);
assert.equal(comparison.subjectCashDelta, 0);
assert.equal(comparison.subjectHullDelta, 0);
assert.deepEqual(sampleShieldExchange(candidate.engine, shieldOptions), normal);
const secondSeat = sampleShieldExchange(candidate.engine, { ...shieldOptions, subjectId: 'p2' });
assert.equal(secondSeat.trace[0].kind, 'fire');
assert.equal(secondSeat.trace[1].weapon, 'shield');

// The candidate does not invent a new purchase lock or alter a bundle.
const shop = candidate.engine.clone();
shop.getState().tanks[0].credits = 30_000; // Synthetic purchase test, not study fixture.
assert.ok(shop.applyAction({ type: 'buy', weapon: 'heavy_shield' }));
assert.equal(shop.getState().tanks[0].credits, 0);
assert.equal(shop.getState().tanks[0].inventory.heavy_shield.count, 2);
assert.ok(shop.applyAction({ type: 'use_shield', weapon: 'heavy_shield' }));
assert.equal(shop.getState().tanks[0].shieldHp, 240);
assert.equal(shop.getState().activePlayerId, 'p2');

// Held-only policy does not buy missing defenses or consume ineffective ones.
const empty = candidate.engine.clone();
empty.getState().tanks[0].inventory.shield.count = 0;
empty.getState().tanks[0].credits = 30_000;
const noDefense = sampleShieldExchange(empty, shieldOptions);
assert.equal(noDefense.shieldActivated, false);
assert.equal(noDefense.trace[0].kind, 'fire');
assert.equal(noDefense.purchases.length, 0);
assert.equal(noDefense.fallbacks[0].reason, 'no-beneficial-held-shield');
const fullPool = stock.engine.clone();
fullPool.getState().tanks[0].shieldHp = 240;
assert.equal(sampleShieldExchange(fullPool, shieldOptions).shieldActivated, false);

// Current normal-shield-only CPU is a separate policy, not the experiment actor.
for (const difficulty of ['easy', 'medium', 'hard']) {
  for (const hull of [30, 100]) {
    const a = stock.engine.clone();
    const b = candidate.engine.clone();
    a.getState().tanks[0].health = hull;
    b.getState().tanks[0].health = hull;
    assert.deepEqual(computeAiPlan(a.getState(), 'p1', difficulty, a.getEffectiveGravity()),
      computeAiPlan(b.getState(), 'p1', difficulty, b.getEffectiveGravity()),
      'removing free heavy must not be described as changed shipped-CPU decision logic');
  }
}

for (const commitmentsPerSeat of [0, 7, NaN, 2.5]) {
  assert.throws(() => sampleShieldExchange(stock.engine, { ...fixtureOptions, commitmentsPerSeat }), RangeError);
}
assert.throws(() => makeOpeningShieldFixture('open-42', 'unknown'), /Unknown/);
assert.throws(() => runOpeningShieldStudy({ scenarioIds: [] }), /known unique/);
assert.throws(() => runOpeningShieldStudy({ weaponIds: ['missile', 'missile'] }), /known unique/);
assert.throws(() => compareOpeningShield(heavy, { ...normal, subjectId: 'p2' }), /matched/);
assert.throws(() => compareOpeningShield(heavy, { ...normal, limits: { ...normal.limits, commitmentsPerSeat: 3 } }), /matched/);
const badStart = structuredClone(normal);
badStart.start.tanks[0].credits += 1;
assert.throws(() => compareOpeningShield(heavy, badStart), /matched/);
const badControl = structuredClone(fireAfter);
badControl.finish.tanks[0].credits += 1;
assert.throws(() => compareOpeningShield(fireBefore, badControl), /Negative control/);
const unresolvedBefore = sampleShieldExchange(stock.engine, { ...shieldOptions, tickLimit: 1 });
const unresolvedAfter = sampleShieldExchange(candidate.engine, { ...shieldOptions, tickLimit: 1 });
assert.equal(unresolvedAfter.summary, null);
assert.equal(compareOpeningShield(unresolvedBefore, unresolvedAfter).status, 'incomplete');

// A lethal first shot can prevent p2's defense; never count that as shield evidence.
const lethalOptions = { strategy: 'held-shield-first', subjectId: 'p2', weapon: 'heavy_missile',
  fixedAim: { angle: 28, power: 100 }, commitmentsPerSeat: 4 };
const lethalStock = sampleShieldExchange(stock.engine, lethalOptions);
const lethalCandidate = sampleShieldExchange(candidate.engine, lethalOptions);
assert.equal(lethalStock.termination, 'game_over');
assert.equal(lethalStock.shieldActivated, false);
assert.equal(compareOpeningShield(lethalStock, lethalCandidate).status, 'defense-not-executed');
assert.equal(lethalCandidate.trace.length, 1);
assert.deepEqual(stock.engine.getState(), untouched);
assert.deepEqual(WEAPONS, catalog);
assert.equal(candidate.engine.getState().tanks[0].inventory.heavy_shield.count, 0);
// Exercise the CLI dispatcher without running another expensive corpus.
// Each selected runner must reject an unknown scenario with its own message;
// a self-referential dispatcher or accidental fall-through cannot pass.
for (const [study, message] of [
  [null, 'Unknown balance scenario'],
  ['single-salvo', 'Unknown balance scenario'],
  ['shield-exchange', 'Unknown exchange scenario'],
  ['opening-shield', 'Select known unique nonempty opening scenarios'],
]) {
  const processResult = spawnSync(process.execPath, [...process.execArgv,
    fileURLToPath(new URL('../balance/run.mjs', import.meta.url)),
    ...(study ? [`--study=${study}`] : []), '--scenario=invalid-fixture'],
  { encoding: 'utf8', timeout: 15_000 });
  assert.equal(processResult.status, 1);
  assert.ok(processResult.stderr.includes(message), processResult.stderr);
  assert.equal(processResult.stdout, '');
}
console.log('OPENING SHIELD CHECK: PASSED (WB-03 paired intervention, controls, costs, bounds and non-execution)');
